---
user: scriptkiddie
group: scriptkiddie

# common apt packages to install
common_apt_packages:
  - tmux
  - xrdp
  - tcpdump
  - tshark
    
# pip packages    
common_pip_packages:
  - poetry

# Common git repos 
common_git_repos: []
  # - {path: "/opt/recon-tools", dir_name: "defaultcredsearch", repo: "https://github.com/ihebski/DefaultCreds-cheat-sheet.git"}

# https://github.com/lgandx/Responder
# https://github.com/CoreSecurity/impacket

# pip install (git packages with a setup.py or pyproject.toml)
common_pip_install: []
  # - {path: "/opt/recon-tools/defaultcredsearch"}

# python setup (git packages with only requirements.txt)
common_python_setup: []

# Create symlinks for python tools installed via setup.py/pyproject.toml or pip
# Multiple aliases can be created for the same tool by adding multiple entries with the same path but different alias and script values
common_python_script_symlinks: []

# Symlinks for git tools
common_git_symlinks: []
# - {src: "/opt/recon-tools/defaultcredsearch/creds", dest: "creds"}


# GoLang Tools -- Only on external
common_go_tools: []

# Docker images to pull
common_install_docker: false
common_docker_images: []

# Burp Suite variables
common_install_burp: false
common_burpsuite_version: "2026.3.2"
common_burpsuite_install_dir: "/opt/burpsuite"

