---
# Change the group name to match the group vars you want to use
trixie:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: python3
      user: ${USER}
      group: ${USER}
