---
# Group ownership for the tools that are installed directly to /opt
group: <user_group> 
user: <user_name>

# common apt packages to install
wl_apt_packages:
  - tmux
  - tree

  # searchsploit
  # - exploitdb 
  # - exploitdb-bin-sploits 
  # - exploitdb-papers
    
# pip packages    
wl_pip_packages:
  - defaultcreds-cheat-sheet

# Common Role git repos 
wl_git_repos:
  - {path: "/opt/wordlist-tools", dir_name: "cupp", repo: "https://github.com/Mebus/cupp.git"}
  - {path: "/opt/wordlist-tools", dir_name: "username-anarchy", repo: "https://github.com/urbanadventurer/username-anarchy.git"}
  - {path: "/opt/wordlist-tools", dir_name: "wister", repo: "https://github.com/cycurity/wister.git"}
  - {path: "/opt/web-tools", dir_name: "wappalyzer-cli", repo: "https://github.com/gokulapap/wappalyzer-cli.git"}


# symlink to a file in the git repos
wl_git_symlinks:
  - {src: "/opt/wordlist-tools/cupp/cupp.py", dest: "/usr/local/bin/cupp"}
  - {src: "/opt/wordlist-tools/username-anarchy/username-anarchy", dest: "/usr/local/bin/username-anarchy"}

# pip install
wl_git_pip_install:
  - {path: "/opt/wordlist-tools/wappalyzer-cli", alias: "wappy", script: "wappalyzer-cli.py"}

# python setup
wl_git_python_setup: []


