---
- name: Check if Burp Suite is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/BurpSuiteCommunity"
  register: burpsuite_installed


# Copied and adapted from https://github.com/iesplin/ansible-role-burpsuite.git
- name: Install Burp Suite Community Edition
  when: common_install_burp and not burpsuite_installed.stat.exists
  block:
    - name: Install package dependencies
      ansible.builtin.apt:
        name:
          - libfontconfig1
          - libfreetype6
          - python3-defusedxml
          - python3-pexpect
        state: present
      become: true

    - name: Download Burp Suite installer for amd64
      when: ansible_architecture == "x86_64"
      ansible.builtin.get_url:
        url: "https://portswigger.net/burp/releases/download?product=community&type=Linux"
        dest: "/tmp/burpsuite_community_linux_setup.sh"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0640'
        timeout: 120

    - name: Download Burp Suite installer for aarch64
      when: ansible_architecture == "aarch64"
      ansible.builtin.get_url:
        url: "https://portswigger.net/burp/releases/download?product=community&type=LinuxArm64"
        dest: "/tmp/burpsuite_community_linux_setup.sh"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0640'
        timeout: 120

    - name: Create response.varfile for unattended install
      ansible.builtin.template:
        src: burpsuite_response.varfile.j2
        dest: /tmp/burpsuite_response.varfile
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0640'

    - name: Install Burp Suite
      ansible.builtin.command:
        cmd: "/bin/sh /tmp/burpsuite_community_linux_setup.sh -q -varfile burpsuite_response.varfile -overwrite"
        chdir: /tmp
      changed_when: true
      become: true
      become_user: "{{ ansible_user_id }}"

    - name: Clean-up files used for installation
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/burpsuite_community_linux_setup.sh
        - /tmp/burpsuite_response.varfile
