---  
- name: apt-update packages
  when: common_apt_packages | length > 0
  ansible.builtin.apt:
    update_cache: yes
  notify: Remove useless apt cache

- name: Install multiple apt packages
  when: common_apt_packages | length > 0
  ansible.builtin.apt:
    update_cache: yes
    # force_apt_get: yes
    install_recommends: yes
    name: "{{ item }}"
    state: latest 
  loop: "{{ common_apt_packages }}"
  notify: 
    - Remove useless apt cache
    - Remove unused apt dependencies

# - name: Update local Database
#   when: common_apt_packages | length > 0
#   ansible.builtin.command: updatedb



