---
- name: "Check if Docker should be installed"
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_stat

- name: "Install docker"
  when: common_install_docker and not docker_stat.stat.exists
  block:
    - name: Install Docker using convenience script
      become: true
      ansible.builtin.shell: "curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh"
      args:
        executable: /bin/bash

    - name: Delete Docker convenience script
      become: true
      ansible.builtin.file:
        path: get-docker.sh
        state: absent

    - name: Start the docker service
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      notify: Docker service up and running

    - name: Make sure the docker group exists
      become: true
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: "Add {{ ansible_user_id }} to docker group"
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

- name: Pull specified Docker images
  when: common_docker_images | length > 0
  block:
    - name: Pull Docker images
      ansible.builtin.docker_image:
        name: "{{ item }}"
        source: pull
      loop: "{{ common_docker_images }}"
      loop_control:
        label: "{{item}}"