# roles/common/main.yml
---
- name: apt tasks 
  when: common_apt_packages | length > 0
  become: True
  ansible.builtin.import_tasks: apt.yml
  
- name: Set Environment Variables in .bashrc file 
  become: True
  ansible.builtin.import_tasks: env.yml

- name: Python Packages
  when: common_pip_packages | length > 0
  ansible.builtin.import_tasks: pip.yml
  
- name: Install Tools from GitHub
  when: common_git_repos | length > 0
  ansible.builtin.import_tasks: git.yml

- name: Install Wireshark, Tcpdump and Tshark
  when: common_install_wireshark| default(false)
  ansible.builtin.import_tasks: wireshark.yml

- name: Install BurpSuite
  when: common_install_burp | default(false)
  ansible.builtin.import_tasks: burp.yml

