# roles/common/main.yml
---
- name: apt tasks 
  when: int_apt_packages | length > 0
  become: True
  ansible.builtin.import_tasks: apt.yml

- name: Python Packages
  when: int_pip_packages | length > 0
  ansible.builtin.import_tasks: pip.yml
  
- name: Install Tools from GitHub
  when: int_git_repos | length > 0
  ansible.builtin.import_tasks: git.yml

- name: Install Go Tools
  when: int_go_tools | length > 0
  become: True
  ansible.builtin.import_tasks: golang.yml
