---
# bash_setup
bash_user: <user_name>

# Group ownership for the tools that are installed directly to /opt
group: <user_group> 
user: <user_name>

# common apt packages to install
common_apt_packages:
  - tmux
  - tree
    
# pip packages    
common_pip_packages:
  - defaultcreds-cheat-sheet

# Common Role git repos 
common_git_repos: []
# https://github.com/lgandx/Responder
# https://github.com/CoreSecurity/impacket

# pip install
common_pip_install:
  - {path: "/opt/web-tools/wappalyzer-cli", alias: "wappy", script: "wappalyzer-cli.py"}

# python setup
common_python_setup: []

# Symlinks for git tools that are not installed via pip or setup.py
common_git_symlinks: []

# GoLang Tools -- Only on external
common_go_tools: []

