---
common_apt_packages: []
common_pip_packages: []
  # - dirhunt
  # - getsploit
  # - poetry
  # - python3-ldap
  # - python-libpcap
  # - pywhat

common_install_docker: false
common_install_wireshark: false
common_install_burp: false
