---
bash_setup: true
tmux_setup: true
nvim_setup: true

install_common_packages: false
common_install_tmux_workspace: false
common_install_wireshark: false
common_install_burp: false
install_internal_packages: false
install_external_packages: false
install_wireless_packages: false 
